name: Validations

on: 
  pull_request_target:
    branches: [main]
    types: [opened, reoneped, edited, synchronized]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Run SwiftLint
        run: swiftlint lint --reporter github-actions-logging

  danger: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: docker://frmeloni/danger-swift-with-swiftlint:3.15.0
        with:
            args: --failOnErrors --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
