name: Validations

on:
  pull_request_target:
    branches: [main]
    types: [opened, reoneped, edited, synchronized]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          DIFF_BASE: ${{ github.base_ref }}
      - name: GitHub Action for SwiftLint with --reporter
        uses: norio-nomura/action-swiftlint@3.2.1
        args: --reporter github-actions-logging
  Danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v5.10 # Look at the `Note for version`
        with:
          args: --failOnErrors --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
