name: Validations

on:
  pull_request_target:
    branches: [main]
    types: [opened, reoneped, edited, synchronized]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action for SwiftLint with --reporter
        uses: norio-nomura/action-swiftlint@3.2.1
        args: --reporter github-actions-logging

  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: docker://frmeloni/danger-swift-with-swiftlint:3.15.0
        with:
          args: --failOnErrors --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
