name: Validations

on:
  pull_request_target:
    branches: [main]
    types: [opened, reoneped, edited, synchronized]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.2.1

  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v5.10 # Look at the `Note for version`
        with:
          args: --failOnErrors --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
